
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-k8s-app
  template:
    metadata:
      labels:
        app: docker-k8s-app
    spec:
      containers:
        - name: docker-k8s-app
          image: dipalisawant/my-docker-k8s-app:latest  # Docker Hub image
          ports:
            - containerPort: 3000
